"""init

Revision ID: a76f3d845998
Revises: 
Create Date: 2025-02-27 15:57:21.531134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76f3d845998'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acomodacao',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.TEXT(), nullable=False),
    sa.Column('price_per_night', sa.Numeric(), nullable=False),
    sa.Column('locale', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acomodacao')
    # ### end Alembic commands ###
