"""init

Revision ID: dd047d4595f3
Revises: a76f3d845998
Create Date: 2025-02-28 00:31:02.455304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd047d4595f3'
down_revision = 'a76f3d845998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.TEXT(), nullable=False),
    sa.Column('price_per_night', sa.Numeric(), nullable=False),
    sa.Column('locale', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accommodation')
    # ### end Alembic commands ###
